import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "./components/Nav";
import Footer from "./components/Footer";
import "@fortawesome/fontawesome-svg-core/styles.css";
import MyFooter from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Avalon",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Nav />
        {children}
        <MyFooter />
      </body>
    </html>
  );
}

export default RootLayout;
